chore(husky#003): Configurar husky y validación de commits

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,10 @@
 
+
 echo "Ejecutando pre-commit hook"
 
 # Aquí se pueden agregar otras validaciones, como ejecutar pruebas
 # echo "Paso 1: Corriendo pnpm test"
-# if ! pnpm test; then
-#   echo "Error: Las pruebas han fallado"
+# if ! pnpm test; entonces echo "Error: Las pruebas han fallado"
 #   exit 1
 # fi
 
